const data = [
    {
      id: 1,
      name: 'Wireless Headphones',
      price: '$79.99',
      category: 'Books',
      stock: '5',
      description: 'hel ddd sdefe daee',
    },
    {
      id: 2,
      name: 'USB-C Cable',
      price: '$12.99',
      category: 'Clothing',
      stock: '26',
      description: 'hel ddd sdefe daee',
    },
    {
      id: 3,
      name: 'Laptop Stand',
      price: '$49.99',
      category: 'Home',
      stock: '59',
      description: 'hel ddd sdefe daee',
    },
    {
      id: 4,
      name: 'Mechanical Keyboard',
      price: '$129.99',
      category: 'Electronics',
      stock: '0',
      description: 'hel ddd sdefe daee',
    },
    {
      id: 5,
      name: 'Monitor Lamp',
      price: '$34.99',
      category: 'Sports',
      stock: '10',
      description: 'hel ddd sdefe daee',
    },
    {
      id: 6,
      name: 'Phone Case',
      price: '$24.99',
      category: 'Clothing',
      stock: '0',
      description: 'hel ddd sdefe daee',
    },
    {
      id: 7,
      name: 'Screen Protector',
      price: '$9.99',
      category: 'Clothing',
      stock: '1',
      description: 'hel ddd sdefe daee',
    },
    {
      id: 8,
      name: 'Portable Charger',
      price: '$45.99',
      category: 'Electronics',
      stock: '3',
      description: 'hel ddd sdefe daee',
    },
    {
      id: 9,
      name: 'Desk Organizer',
      price: '$29.99',
      category: 'Home',
      stock: '0',
      description: 'hel ddd sdefe daee',
    },
    {
      id: 10,
      name: 'Mouse Pad',
      price: '$19.99',
      category: 'Clothing',
      stock: '55',
      description: 'hel ddd sdefe daee',
    },
    {
      id: 11,
      name: 'Webcam',
      price: '$89.99',
      category: 'Toys',
      stock: '100',
      description: 'hel ddd sdefe daee',
    },
    {
      id: 12,
      name: 'Document Holder',
      price: '$22.99',
      category: 'Home',
      stock: '29',
      description: 'hel ddd sdefe daee',
    },
  ]

  export default data